<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.data.build</groupId>
        <artifactId>spring-data-parent</artifactId>
        <version>3.5.4</version>
        <relativePath/>
    </parent>

    <groupId>org.springframework</groupId>
    <artifactId>spring-airtable</artifactId>
    <packaging>pom</packaging>

    <name>Spring Airtable</name>
    <description>Spring Data integration with Airtable</description>
    <url>https://github.com/manish-in-java/spring-data-redis</url>

    <build>
        <pluginManagement>
            <plugins>

                <!--
                  Used for running unit and integration tests.
                -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven.plugin.surefire.version}</version>
                    <configuration>
                        <failIfNoTests>false</failIfNoTests>
                        <useSystemClassLoader>false</useSystemClassLoader>
                    </configuration>
                </plugin>

                <!--
                    Provides code coverage while running tests.
                -->
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencies>
        <!--
            Provides code coverage while running tests.
        -->
        <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>org.jacoco.agent</artifactId>
            <version>${jacoco.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
            <comments>Copyright 2008-2020 the original author or authors. Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in
                compliance with the License. You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in
                writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
                License for the specific language governing permissions and limitations under the License.
            </comments>
        </license>
    </licenses>

    <modules>
        <module>spring-data-airtable</module>
        <module>spring-boot-starter-data-airtable</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <java.version>22</java.version>

        <maven.plugin.surefire.version>3.5.2</maven.plugin.surefire.version>

        <jacoco.version>0.8.12</jacoco.version>
    </properties>
</project>
