<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework</groupId>
        <artifactId>spring-airtable</artifactId>
        <version>3.5.4</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-airtable</artifactId>

    <name>Spring Data Airtable</name>
    <description>Spring Data module for Airtable</description>

    <build>
        <plugins>
            <!--
              Used for running unit and integration tests.
            -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>${unit-test-agent}</argLine>
                </configuration>
            </plugin>

            <!--
                Provides code coverage while running tests.
            -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <destFile>${project.reporting.outputDirectory}/coverage.exec</destFile>
                            <propertyName>unit-test-agent</propertyName>
                        </configuration>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <id>pre-test</id>
                    </execution>
                    <execution>
                        <configuration>
                            <dataFile>${project.reporting.outputDirectory}/coverage.exec</dataFile>
                            <outputDirectory>${project.reporting.outputDirectory}/coverage</outputDirectory>
                        </configuration>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <id>post-test</id>
                        <phase>test</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>${spring}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-commons</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>
